### ISSUE TITLE
PNG file customised title

### ISSUE THREAD

**Issue by AlperErg** [AlperErg/EXPgrapher#10]
Problem:
When a graph is downloaded, it always has the name "MyGraph". This makes it difficult to identify different graph photos locally unless they are manually named every time they are downloaded.
Solution:
The photo files could have the title of the custom graph.

**Comment by Tharuneshwarv** [comment]
@AlperErg can i work on this issue ?

**Comment by AlperErg** [comment]
@Tharuneshwarv Yeah go ahead, I would appreciate it.

**Comment by Tharuneshwarv** [comment]
@AlperErg I have added PR for this issue https://github.com/AlperErg/EXPgrapher/pull/11 . Please Review it.

**Comment by AlperErg** [comment]
It works well, thank you for the simple addition.
